# Changes here will be overwritten by Copier
_commit: 798dc24
_src_path: gh:34j/pypackage-template
add_me_as_contributor: false
copyright_year: '2025'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_app_installation_ids: 31487150,37771054
github_username: 34j
has_cli: false
initial_commit: false
is_django_package: false
open_source_license: MIT
open_with_editor: true
package_name: matplotlib_multicolored_line
project_name: Matplotlib Multicolored Line
project_short_description: Plot multicolored lines in Matplotlib
project_slug: matplotlib-multicolored-line
run_uv_sync: false
setup_github: false
setup_pre_commit: false

